title: К. Волков / Визитка
profile_img: /assets/img/profile.webp
icon_img: /assets/img/calendar.webp

name: "Кирилл Волков"
job: "Старший IT-менеджер"

phone_number: +123456789
address: Россия, Москва
email: email@example.com
linkedin_username: linkedin
github_username: github
instagram_username: instagram
twitter_username: twitter
facebook_username: facebook
youtube_username: youtube
telegram_username: kvolkov_cs
blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl: /prodman

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
